[book]
authors = ["Tahlon Brahic"]
description = "Nix modules that abstract the arduous Linux customization experience"
title = "kosei"

[build]
extra-watch-dirs = ["."]

[output.html]
edit-url-template = "https://github.com/TahlonBrahic/fuyu-no-kosei/edit/main/docs/{path}"
git-repository-url = "https://github.com/TahlonBrahic/fuyu-no-kosei"
preferred-dark-theme = "ayu"
site-url = "/kosei/"
