[book]
authors = ["Tahlon Brahic"]
description = "Nix modules that abstract the arduous Linux customization experience"
title = "frostbite"

[build]
extra-watch-dirs = ["."]

[output.html]
edit-url-template = "https://github.com/cryomancy/frostbite/edit/main/docs/{path}"
git-repository-url = "https://github.com/cryomancy/frostbite"
preferred-dark-theme = "ayu"
site-url = "/frostbite/"
